package io.github.trueliquid.compose

import androidx.compose.ui.unit.dp

object TrueLiquidDefaults {
    val windowWidth = 780.dp
    val collapsedHeight = 120.dp
    val expandedHeight = 530.dp
    val contentPadding = 10.dp

    fun spotlightStyle(
        glassAlpha: Float = 0.86f,
        tintAlpha: Float = 0.08f,
        refraction: Float = 0.56f,
        curve: Float = 0.76f,
        dispersion: Float = 0.24f,
        frost: Float = 0.06f,
        blur: Float = 0.01f,
        saturation: Float = 1.16f,
        contrast: Float = 0.05f,
        luminanceClamp: Float = 0.28f,
        edge: Float = 0.32f,
        depth: Float = 0.78f,
        innerShadow: Float = 0.46f,
        outerShadow: Float = 0f,
        cornerRadius: Float = 34f,
        captureScale: Float = 0.82f,
        fps: Int = 60,
        mode: TrueLiquidMode = TrueLiquidMode.CaptureShader,
    ) = TrueLiquidStyle(
        glassAlpha = glassAlpha,
        tintAlpha = tintAlpha,
        refraction = refraction,
        curve = curve,
        dispersion = dispersion,
        frost = frost,
        blur = blur,
        saturation = saturation,
        contrast = contrast,
        luminanceClamp = luminanceClamp,
        edge = edge,
        depth = depth,
        innerShadow = innerShadow,
        outerShadow = outerShadow,
        cornerRadius = cornerRadius,
        captureScale = captureScale,
        fps = fps,
        mode = mode,
    )

    fun clearLensStyle(
        glassAlpha: Float = 0.94f,
        tintAlpha: Float = 0.00f,
        refraction: Float = 0.36f,
        curve: Float = 0.58f,
        dispersion: Float = 0.09f,
        frost: Float = 0.10f,
        blur: Float = 0.015f,
        saturation: Float = 1.04f,
        contrast: Float = 0.02f,
        luminanceClamp: Float = 0.40f,
        edge: Float = 0.18f,
        depth: Float = 0.58f,
        innerShadow: Float = 0.34f,
        outerShadow: Float = 0f,
        cornerRadius: Float = 34f,
        captureScale: Float = 0.82f,
        fps: Int = 60,
        mode: TrueLiquidMode = TrueLiquidMode.CaptureShader,
    ) = spotlightStyle(
        glassAlpha = glassAlpha,
        tintAlpha = tintAlpha,
        refraction = refraction,
        curve = curve,
        dispersion = dispersion,
        frost = frost,
        blur = blur,
        saturation = saturation,
        contrast = contrast,
        luminanceClamp = luminanceClamp,
        edge = edge,
        depth = depth,
        innerShadow = innerShadow,
        outerShadow = outerShadow,
        cornerRadius = cornerRadius,
        captureScale = captureScale,
        fps = fps,
        mode = mode,
    )

    fun prismStyle(
        glassAlpha: Float = 0.86f,
        tintAlpha: Float = 0.08f,
        refraction: Float = 0.56f,
        curve: Float = 0.76f,
        dispersion: Float = 0.24f,
        frost: Float = 0.06f,
        blur: Float = 0.01f,
        saturation: Float = 1.16f,
        contrast: Float = 0.05f,
        luminanceClamp: Float = 0.28f,
        edge: Float = 0.32f,
        depth: Float = 0.78f,
        innerShadow: Float = 0.46f,
        outerShadow: Float = 0f,
        cornerRadius: Float = 34f,
        captureScale: Float = 0.82f,
        fps: Int = 60,
        mode: TrueLiquidMode = TrueLiquidMode.CaptureShader,
    ) = spotlightStyle(
        glassAlpha = glassAlpha,
        tintAlpha = tintAlpha,
        refraction = refraction,
        curve = curve,
        dispersion = dispersion,
        frost = frost,
        blur = blur,
        saturation = saturation,
        contrast = contrast,
        luminanceClamp = luminanceClamp,
        edge = edge,
        depth = depth,
        innerShadow = innerShadow,
        outerShadow = outerShadow,
        cornerRadius = cornerRadius,
        captureScale = captureScale,
        fps = fps,
        mode = mode,
    )

    fun nativeGlassStyle(
        glassAlpha: Float = 0.78f,
        tintAlpha: Float = 0.16f,
        cornerRadius: Float = 34f,
    ) = spotlightStyle(
        glassAlpha = glassAlpha,
        tintAlpha = tintAlpha,
        cornerRadius = cornerRadius,
        mode = TrueLiquidMode.NativeGlass,
    )
}
